// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SCA_MVC.Data;

#nullable disable

namespace SCA_MVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260225224902_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SCA_MVC.Models.Empleado", b =>
                {
                    b.Property<int>("IdEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpleado"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("IdCredencial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdEmpleado");

                    b.HasIndex("IdCredencial")
                        .IsUnique()
                        .HasDatabaseName("IX_Empleado_IdCredencial");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("Empleados");

                    b.HasData(
                        new
                        {
                            IdEmpleado = 1,
                            Apellido = "Perez",
                            Estado = true,
                            IdCredencial = "RF001",
                            IdEmpresa = 1,
                            Nombre = "Juan"
                        },
                        new
                        {
                            IdEmpleado = 2,
                            Apellido = "García",
                            Estado = true,
                            IdCredencial = "RF002",
                            IdEmpresa = 1,
                            Nombre = "María"
                        },
                        new
                        {
                            IdEmpleado = 3,
                            Apellido = "López",
                            Estado = true,
                            IdCredencial = "RF003",
                            IdEmpresa = 1,
                            Nombre = "Carlos"
                        },
                        new
                        {
                            IdEmpleado = 4,
                            Apellido = "Martínez",
                            Estado = true,
                            IdCredencial = "RF004",
                            IdEmpresa = 1,
                            Nombre = "Ana"
                        },
                        new
                        {
                            IdEmpleado = 5,
                            Apellido = "Rodríguez",
                            Estado = true,
                            IdCredencial = "RF005",
                            IdEmpresa = 1,
                            Nombre = "Luis"
                        },
                        new
                        {
                            IdEmpleado = 6,
                            Apellido = "Fernández",
                            Estado = true,
                            IdCredencial = "RF006",
                            IdEmpresa = 1,
                            Nombre = "Sofía"
                        },
                        new
                        {
                            IdEmpleado = 7,
                            Apellido = "González",
                            Estado = true,
                            IdCredencial = "RF007",
                            IdEmpresa = 1,
                            Nombre = "Diego"
                        },
                        new
                        {
                            IdEmpleado = 8,
                            Apellido = "Silva",
                            Estado = true,
                            IdCredencial = "RF008",
                            IdEmpresa = 1,
                            Nombre = "Valentina"
                        },
                        new
                        {
                            IdEmpleado = 9,
                            Apellido = "Morales",
                            Estado = true,
                            IdCredencial = "RF009",
                            IdEmpresa = 1,
                            Nombre = "Andrés"
                        },
                        new
                        {
                            IdEmpleado = 10,
                            Apellido = "Vargas",
                            Estado = true,
                            IdCredencial = "RF010",
                            IdEmpresa = 1,
                            Nombre = "Camila"
                        },
                        new
                        {
                            IdEmpleado = 11,
                            Apellido = "Herrera",
                            Estado = true,
                            IdCredencial = "RF011",
                            IdEmpresa = 2,
                            Nombre = "Roberto"
                        },
                        new
                        {
                            IdEmpleado = 12,
                            Apellido = "Castro",
                            Estado = true,
                            IdCredencial = "RF012",
                            IdEmpresa = 2,
                            Nombre = "Patricia"
                        },
                        new
                        {
                            IdEmpleado = 13,
                            Apellido = "Torres",
                            Estado = true,
                            IdCredencial = "RF013",
                            IdEmpresa = 3,
                            Nombre = "Miguel"
                        },
                        new
                        {
                            IdEmpleado = 14,
                            Apellido = "Reyes",
                            Estado = true,
                            IdCredencial = "RF014",
                            IdEmpresa = 4,
                            Nombre = "Isabella"
                        },
                        new
                        {
                            IdEmpleado = 15,
                            Apellido = "Jiménez",
                            Estado = true,
                            IdCredencial = "RF015",
                            IdEmpresa = 5,
                            Nombre = "Francisco"
                        },
                        new
                        {
                            IdEmpleado = 16,
                            Apellido = "Moreno",
                            Estado = true,
                            IdCredencial = "RF016",
                            IdEmpresa = 6,
                            Nombre = "Daniela"
                        });
                });

            modelBuilder.Entity("SCA_MVC.Models.Empresa", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpresa"));

                    b.Property<int>("CantidadEmpleados")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdEmpresa");

                    b.ToTable("Empresas");

                    b.HasData(
                        new
                        {
                            IdEmpresa = 1,
                            CantidadEmpleados = 0,
                            Estado = true,
                            Nombre = "Roemmers"
                        },
                        new
                        {
                            IdEmpresa = 2,
                            CantidadEmpleados = 0,
                            Estado = true,
                            Nombre = "Gema"
                        },
                        new
                        {
                            IdEmpresa = 3,
                            CantidadEmpleados = 0,
                            Estado = true,
                            Nombre = "Siegfried"
                        },
                        new
                        {
                            IdEmpresa = 4,
                            CantidadEmpleados = 0,
                            Estado = true,
                            Nombre = "Gramon"
                        },
                        new
                        {
                            IdEmpresa = 5,
                            CantidadEmpleados = 0,
                            Estado = true,
                            Nombre = "Simmer"
                        },
                        new
                        {
                            IdEmpresa = 6,
                            CantidadEmpleados = 0,
                            Estado = true,
                            Nombre = "Ethical"
                        });
                });

            modelBuilder.Entity("SCA_MVC.Models.Lugar", b =>
                {
                    b.Property<int>("IdLugar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLugar"));

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdLugar");

                    b.ToTable("Lugares");

                    b.HasData(
                        new
                        {
                            IdLugar = 1,
                            Estado = true,
                            Nombre = "Comedor"
                        },
                        new
                        {
                            IdLugar = 2,
                            Estado = true,
                            Nombre = "Quincho"
                        });
                });

            modelBuilder.Entity("SCA_MVC.Models.Registro", b =>
                {
                    b.Property<int>("IdRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRegistro"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Hora")
                        .HasColumnType("time");

                    b.Property<int?>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int>("IdLugar")
                        .HasColumnType("int");

                    b.Property<int>("IdServicio")
                        .HasColumnType("int");

                    b.HasKey("IdRegistro");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdLugar");

                    b.HasIndex("IdServicio");

                    b.HasIndex("IdEmpleado", "IdServicio")
                        .IsUnique()
                        .HasDatabaseName("IX_Registro_Empleado_Servicio")
                        .HasFilter("[IdEmpleado] IS NOT NULL");

                    b.ToTable("Registros");

                    b.HasData(
                        new
                        {
                            IdRegistro = 1,
                            Fecha = new DateTime(2026, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hora = new TimeSpan(0, 12, 11, 0, 0),
                            IdEmpleado = 1,
                            IdEmpresa = 1,
                            IdLugar = 1,
                            IdServicio = 1
                        },
                        new
                        {
                            IdRegistro = 2,
                            Fecha = new DateTime(2026, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hora = new TimeSpan(0, 12, 12, 0, 0),
                            IdEmpleado = 2,
                            IdEmpresa = 1,
                            IdLugar = 1,
                            IdServicio = 1
                        },
                        new
                        {
                            IdRegistro = 3,
                            Fecha = new DateTime(2026, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hora = new TimeSpan(0, 12, 13, 0, 0),
                            IdEmpleado = 3,
                            IdEmpresa = 1,
                            IdLugar = 1,
                            IdServicio = 1
                        },
                        new
                        {
                            IdRegistro = 4,
                            Fecha = new DateTime(2026, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hora = new TimeSpan(0, 12, 14, 0, 0),
                            IdEmpleado = 4,
                            IdEmpresa = 1,
                            IdLugar = 1,
                            IdServicio = 1
                        },
                        new
                        {
                            IdRegistro = 5,
                            Fecha = new DateTime(2026, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hora = new TimeSpan(0, 12, 15, 0, 0),
                            IdEmpleado = 5,
                            IdEmpresa = 1,
                            IdLugar = 1,
                            IdServicio = 1
                        },
                        new
                        {
                            IdRegistro = 6,
                            Fecha = new DateTime(2026, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hora = new TimeSpan(0, 13, 11, 0, 0),
                            IdEmpleado = 6,
                            IdEmpresa = 1,
                            IdLugar = 2,
                            IdServicio = 2
                        },
                        new
                        {
                            IdRegistro = 7,
                            Fecha = new DateTime(2026, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hora = new TimeSpan(0, 13, 12, 0, 0),
                            IdEmpleado = 7,
                            IdEmpresa = 1,
                            IdLugar = 2,
                            IdServicio = 2
                        },
                        new
                        {
                            IdRegistro = 8,
                            Fecha = new DateTime(2026, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hora = new TimeSpan(0, 13, 13, 0, 0),
                            IdEmpleado = 8,
                            IdEmpresa = 1,
                            IdLugar = 2,
                            IdServicio = 2
                        },
                        new
                        {
                            IdRegistro = 9,
                            Fecha = new DateTime(2026, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hora = new TimeSpan(0, 12, 11, 0, 0),
                            IdEmpleado = 1,
                            IdEmpresa = 1,
                            IdLugar = 1,
                            IdServicio = 3
                        },
                        new
                        {
                            IdRegistro = 10,
                            Fecha = new DateTime(2026, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hora = new TimeSpan(0, 12, 12, 0, 0),
                            IdEmpleado = 2,
                            IdEmpresa = 1,
                            IdLugar = 1,
                            IdServicio = 3
                        },
                        new
                        {
                            IdRegistro = 11,
                            Fecha = new DateTime(2026, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hora = new TimeSpan(0, 12, 13, 0, 0),
                            IdEmpleado = 3,
                            IdEmpresa = 1,
                            IdLugar = 1,
                            IdServicio = 3
                        },
                        new
                        {
                            IdRegistro = 12,
                            Fecha = new DateTime(2026, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hora = new TimeSpan(0, 12, 14, 0, 0),
                            IdEmpleado = 4,
                            IdEmpresa = 1,
                            IdLugar = 1,
                            IdServicio = 3
                        },
                        new
                        {
                            IdRegistro = 13,
                            Fecha = new DateTime(2026, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hora = new TimeSpan(0, 12, 15, 0, 0),
                            IdEmpleado = 5,
                            IdEmpresa = 1,
                            IdLugar = 1,
                            IdServicio = 3
                        },
                        new
                        {
                            IdRegistro = 14,
                            Fecha = new DateTime(2026, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hora = new TimeSpan(0, 13, 11, 0, 0),
                            IdEmpleado = 6,
                            IdEmpresa = 1,
                            IdLugar = 2,
                            IdServicio = 4
                        },
                        new
                        {
                            IdRegistro = 15,
                            Fecha = new DateTime(2026, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hora = new TimeSpan(0, 13, 12, 0, 0),
                            IdEmpleado = 7,
                            IdEmpresa = 1,
                            IdLugar = 2,
                            IdServicio = 4
                        },
                        new
                        {
                            IdRegistro = 16,
                            Fecha = new DateTime(2026, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hora = new TimeSpan(0, 13, 13, 0, 0),
                            IdEmpleado = 8,
                            IdEmpresa = 1,
                            IdLugar = 2,
                            IdServicio = 4
                        },
                        new
                        {
                            IdRegistro = 17,
                            Fecha = new DateTime(2026, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hora = new TimeSpan(0, 12, 11, 0, 0),
                            IdEmpleado = 1,
                            IdEmpresa = 1,
                            IdLugar = 1,
                            IdServicio = 5
                        },
                        new
                        {
                            IdRegistro = 18,
                            Fecha = new DateTime(2026, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hora = new TimeSpan(0, 12, 12, 0, 0),
                            IdEmpleado = 2,
                            IdEmpresa = 1,
                            IdLugar = 1,
                            IdServicio = 5
                        },
                        new
                        {
                            IdRegistro = 19,
                            Fecha = new DateTime(2026, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hora = new TimeSpan(0, 12, 13, 0, 0),
                            IdEmpleado = 3,
                            IdEmpresa = 1,
                            IdLugar = 1,
                            IdServicio = 5
                        },
                        new
                        {
                            IdRegistro = 20,
                            Fecha = new DateTime(2026, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hora = new TimeSpan(0, 12, 14, 0, 0),
                            IdEmpleado = 4,
                            IdEmpresa = 1,
                            IdLugar = 1,
                            IdServicio = 5
                        },
                        new
                        {
                            IdRegistro = 21,
                            Fecha = new DateTime(2026, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hora = new TimeSpan(0, 12, 15, 0, 0),
                            IdEmpleado = 5,
                            IdEmpresa = 1,
                            IdLugar = 1,
                            IdServicio = 5
                        },
                        new
                        {
                            IdRegistro = 22,
                            Fecha = new DateTime(2026, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hora = new TimeSpan(0, 13, 11, 0, 0),
                            IdEmpleado = 6,
                            IdEmpresa = 1,
                            IdLugar = 2,
                            IdServicio = 6
                        },
                        new
                        {
                            IdRegistro = 23,
                            Fecha = new DateTime(2026, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hora = new TimeSpan(0, 13, 12, 0, 0),
                            IdEmpleado = 7,
                            IdEmpresa = 1,
                            IdLugar = 2,
                            IdServicio = 6
                        },
                        new
                        {
                            IdRegistro = 24,
                            Fecha = new DateTime(2026, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hora = new TimeSpan(0, 13, 13, 0, 0),
                            IdEmpleado = 8,
                            IdEmpresa = 1,
                            IdLugar = 2,
                            IdServicio = 6
                        });
                });

            modelBuilder.Entity("SCA_MVC.Models.Servicio", b =>
                {
                    b.Property<int>("IdServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdServicio"));

                    b.Property<int?>("DuracionMinutos")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HoraInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdLugar")
                        .HasColumnType("int");

                    b.Property<int?>("Proyeccion")
                        .HasColumnType("int");

                    b.Property<int>("TotalComensales")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalInvitados")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("IdServicio");

                    b.HasIndex("IdLugar");

                    b.ToTable("Servicios", t =>
                        {
                            t.HasCheckConstraint("CK_Servicio_Fecha", "[Fecha] <= '2030-01-01'");
                        });

                    b.HasData(
                        new
                        {
                            IdServicio = 1,
                            DuracionMinutos = 60,
                            Fecha = new DateTime(2026, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdLugar = 1,
                            Proyeccion = 50,
                            TotalComensales = 5,
                            TotalInvitados = 1
                        },
                        new
                        {
                            IdServicio = 2,
                            DuracionMinutos = 45,
                            Fecha = new DateTime(2026, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdLugar = 2,
                            Proyeccion = 30,
                            TotalComensales = 3,
                            TotalInvitados = 0
                        },
                        new
                        {
                            IdServicio = 3,
                            DuracionMinutos = 60,
                            Fecha = new DateTime(2026, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdLugar = 1,
                            Proyeccion = 50,
                            TotalComensales = 5,
                            TotalInvitados = 1
                        },
                        new
                        {
                            IdServicio = 4,
                            DuracionMinutos = 45,
                            Fecha = new DateTime(2026, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdLugar = 2,
                            Proyeccion = 30,
                            TotalComensales = 3,
                            TotalInvitados = 0
                        },
                        new
                        {
                            IdServicio = 5,
                            DuracionMinutos = 60,
                            Fecha = new DateTime(2026, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdLugar = 1,
                            Proyeccion = 50,
                            TotalComensales = 5,
                            TotalInvitados = 1
                        },
                        new
                        {
                            IdServicio = 6,
                            DuracionMinutos = 45,
                            Fecha = new DateTime(2026, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdLugar = 2,
                            Proyeccion = 30,
                            TotalComensales = 3,
                            TotalInvitados = 0
                        });
                });

            modelBuilder.Entity("SCA_MVC.Models.Empleado", b =>
                {
                    b.HasOne("SCA_MVC.Models.Empresa", "Empresa")
                        .WithMany("Empleados")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Empleados_Empresa");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("SCA_MVC.Models.Registro", b =>
                {
                    b.HasOne("SCA_MVC.Models.Empleado", "Empleado")
                        .WithMany("Registros")
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Registros_Empleado");

                    b.HasOne("SCA_MVC.Models.Empresa", "Empresa")
                        .WithMany("Registros")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Registros_Empresa");

                    b.HasOne("SCA_MVC.Models.Lugar", "Lugar")
                        .WithMany("Registros")
                        .HasForeignKey("IdLugar")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Registros_Lugar");

                    b.HasOne("SCA_MVC.Models.Servicio", "Servicio")
                        .WithMany("Registros")
                        .HasForeignKey("IdServicio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Registros_Servicio");

                    b.Navigation("Empleado");

                    b.Navigation("Empresa");

                    b.Navigation("Lugar");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("SCA_MVC.Models.Servicio", b =>
                {
                    b.HasOne("SCA_MVC.Models.Lugar", "Lugar")
                        .WithMany("Servicios")
                        .HasForeignKey("IdLugar")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Servicios_Lugar");

                    b.Navigation("Lugar");
                });

            modelBuilder.Entity("SCA_MVC.Models.Empleado", b =>
                {
                    b.Navigation("Registros");
                });

            modelBuilder.Entity("SCA_MVC.Models.Empresa", b =>
                {
                    b.Navigation("Empleados");

                    b.Navigation("Registros");
                });

            modelBuilder.Entity("SCA_MVC.Models.Lugar", b =>
                {
                    b.Navigation("Registros");

                    b.Navigation("Servicios");
                });

            modelBuilder.Entity("SCA_MVC.Models.Servicio", b =>
                {
                    b.Navigation("Registros");
                });
#pragma warning restore 612, 618
        }
    }
}
