// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SCA_MVC.Data;

#nullable disable

namespace SCA_MVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SCA_MVC.Models.Empleado", b =>
                {
                    b.Property<int>("IdEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpleado"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("IdCredencial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdEmpleado");

                    b.HasIndex("IdCredencial")
                        .IsUnique()
                        .HasDatabaseName("IX_Empleado_IdCredencial");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("SCA_MVC.Models.Empresa", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpresa"));

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdEmpresa");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("SCA_MVC.Models.Lugar", b =>
                {
                    b.Property<int>("IdLugar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLugar"));

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdLugar");

                    b.ToTable("Lugares");
                });

            modelBuilder.Entity("SCA_MVC.Models.Registro", b =>
                {
                    b.Property<int>("IdRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRegistro"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Hora")
                        .HasColumnType("time");

                    b.Property<int?>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int>("IdLugar")
                        .HasColumnType("int");

                    b.Property<int>("IdServicio")
                        .HasColumnType("int");

                    b.HasKey("IdRegistro");

                    b.HasIndex("Fecha")
                        .HasDatabaseName("IX_Registro_Fecha");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdLugar");

                    b.HasIndex("IdServicio");

                    b.HasIndex("IdEmpleado", "IdServicio")
                        .IsUnique()
                        .HasDatabaseName("IX_Registro_Empleado_Servicio")
                        .HasFilter("[IdEmpleado] IS NOT NULL");

                    b.ToTable("Registros");
                });

            modelBuilder.Entity("SCA_MVC.Models.Servicio", b =>
                {
                    b.Property<int>("IdServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdServicio"));

                    b.Property<int?>("DuracionMinutos")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdLugar")
                        .HasColumnType("int");

                    b.Property<int?>("Proyeccion")
                        .HasColumnType("int");

                    b.Property<int>("TotalComensales")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalInvitados")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("IdServicio");

                    b.HasIndex("IdLugar");

                    b.HasIndex("Fecha", "IdLugar")
                        .HasDatabaseName("IX_Servicio_Fecha_Lugar");

                    b.ToTable("Servicios", t =>
                        {
                            t.HasCheckConstraint("CK_Servicio_Fecha", "[Fecha] <= CAST(GETDATE() AS DATE)");
                        });
                });

            modelBuilder.Entity("SCA_MVC.Models.Empleado", b =>
                {
                    b.HasOne("SCA_MVC.Models.Empresa", "Empresa")
                        .WithMany("Empleados")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Empleados_Empresa");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("SCA_MVC.Models.Registro", b =>
                {
                    b.HasOne("SCA_MVC.Models.Empleado", "Empleado")
                        .WithMany("Registros")
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Registros_Empleado");

                    b.HasOne("SCA_MVC.Models.Empresa", "Empresa")
                        .WithMany("Registros")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Registros_Empresa");

                    b.HasOne("SCA_MVC.Models.Lugar", "Lugar")
                        .WithMany("Registros")
                        .HasForeignKey("IdLugar")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Registros_Lugar");

                    b.HasOne("SCA_MVC.Models.Servicio", "Servicio")
                        .WithMany("Registros")
                        .HasForeignKey("IdServicio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Registros_Servicio");

                    b.Navigation("Empleado");

                    b.Navigation("Empresa");

                    b.Navigation("Lugar");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("SCA_MVC.Models.Servicio", b =>
                {
                    b.HasOne("SCA_MVC.Models.Lugar", "Lugar")
                        .WithMany("Servicios")
                        .HasForeignKey("IdLugar")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Servicios_Lugar");

                    b.Navigation("Lugar");
                });

            modelBuilder.Entity("SCA_MVC.Models.Empleado", b =>
                {
                    b.Navigation("Registros");
                });

            modelBuilder.Entity("SCA_MVC.Models.Empresa", b =>
                {
                    b.Navigation("Empleados");

                    b.Navigation("Registros");
                });

            modelBuilder.Entity("SCA_MVC.Models.Lugar", b =>
                {
                    b.Navigation("Registros");

                    b.Navigation("Servicios");
                });

            modelBuilder.Entity("SCA_MVC.Models.Servicio", b =>
                {
                    b.Navigation("Registros");
                });
#pragma warning restore 612, 618
        }
    }
}
